version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tx-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: txdb
    ports:
      - '5433:5432'  # Host port 5433 → Container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
