version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tx-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: txdb
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  node-server:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: tx-node
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '5001:5001'
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/txdb
      FLASK_API: http://flask-server:3001
    restart: unless-stopped

  flask-server:
    build:
      context: .
      dockerfile: Dockerfile.python
    container_name: tx-python
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '3001:3001'
    environment:
      FRONTENDIP: http://localhost:3000
    restart: unless-stopped

volumes:
  pgdata:
